/* @constants/themes/themes.ts */
// colour themes

// local
import { colors } from "../colors";

const themes = {
    light: {
        name: "light",
        bg: {
            canvas: colors.basic.white,
            surface: colors.gray.light[100],
            elevated: colors.gray.light[200],
        },
        text: {
            primary: colors.gray.light[950],
            secondary: colors.gray.light[500],
            muted: colors.gray.light[400],
            inverse: colors.basic.white,
        },
        neutral: {
            subtle: colors.gray.light[50],
            faint: colors.gray.light[100],
            soft: colors.gray.light[200],
            muted: colors.gray.light[300],
            gentle: colors.gray.light[400],
            default: colors.gray.light[500],
            vivid: colors.gray.light[600],
            strong: colors.gray.light[700],
            bold: colors.gray.light[800],
            heavy: colors.gray.light[900],
            ink: colors.gray.light[950],
        },
        brand: {
            subtle: colors.blue.light[50],
            faint: colors.blue.light[100],
            soft: colors.blue.light[200],
            muted: colors.blue.light[300],
            gentle: colors.blue.light[400],
            default: colors.blue.light[500],
            vivid: colors.blue.light[600],
            strong: colors.blue.light[700],
            bold: colors.blue.light[800],
            heavy: colors.blue.light[900],
            ink: colors.blue.light[950],
        },
        alt: {
            subtle: colors.pink.light[50],
            faint: colors.pink.light[100],
            soft: colors.pink.light[200],
            muted: colors.pink.light[300],
            gentle: colors.pink.light[400],
            default: colors.pink.light[500],
            vivid: colors.pink.light[600],
            strong: colors.pink.light[700],
            bold: colors.pink.light[800],
            heavy: colors.pink.light[900],
            ink: colors.pink.light[950],
        },
        accent: {
            subtle: colors.purple.light[50],
            faint: colors.purple.light[100],
            soft: colors.purple.light[200],
            muted: colors.purple.light[300],
            gentle: colors.purple.light[400],
            default: colors.purple.light[500],
            vivid: colors.purple.light[600],
            strong: colors.purple.light[700],
            bold: colors.purple.light[800],
            heavy: colors.purple.light[900],
            ink: colors.purple.light[950],
        },
        success: {
            subtle: colors.green.light[50],
            faint: colors.green.light[100],
            soft: colors.green.light[200],
            muted: colors.green.light[300],
            gentle: colors.green.light[400],
            default: colors.green.light[500],
            vivid: colors.green.light[600],
            strong: colors.green.light[700],
            bold: colors.green.light[800],
            heavy: colors.green.light[900],
            ink: colors.green.light[950],
        },
        warning: {
            subtle: colors.orange.light[50],
            faint: colors.orange.light[100],
            soft: colors.orange.light[200],
            muted: colors.orange.light[300],
            gentle: colors.orange.light[400],
            default: colors.orange.light[500],
            vivid: colors.orange.light[600],
            strong: colors.orange.light[700],
            bold: colors.orange.light[800],
            heavy: colors.orange.light[900],
            ink: colors.orange.light[950],
        },
        error: {
            subtle: colors.red.light[50],
            faint: colors.red.light[100],
            soft: colors.red.light[200],
            muted: colors.red.light[300],
            gentle: colors.red.light[400],
            default: colors.red.light[500],
            vivid: colors.red.light[600],
            strong: colors.red.light[700],
            bold: colors.red.light[800],
            heavy: colors.red.light[900],
            ink: colors.red.light[950],
        },
    },
    dark: {
        name: "dark",
        bg: {
            canvas: colors.basic.black,
            surface: colors.gray.dark[900],
            elevated: colors.gray.dark[800],
        },
        text: {
            primary: colors.gray.dark[50],
            secondary: colors.gray.dark[500],
            muted: colors.gray.dark[600],
            inverse: colors.basic.black,
        },
        neutral: {
            subtle: colors.gray.dark[950],
            faint: colors.gray.dark[900],
            soft: colors.gray.dark[800],
            muted: colors.gray.dark[700],
            gentle: colors.gray.dark[600],
            default: colors.gray.dark[500],
            vivid: colors.gray.dark[400],
            strong: colors.gray.dark[300],
            bold: colors.gray.dark[200],
            heavy: colors.gray.dark[100],
            ink: colors.gray.dark[50],
        },
        brand: {
            subtle: colors.blue.dark[950],
            faint: colors.blue.dark[900],
            soft: colors.blue.dark[800],
            muted: colors.blue.dark[700],
            gentle: colors.blue.dark[600],
            default: colors.blue.dark[500],
            vivid: colors.blue.dark[400],
            strong: colors.blue.dark[300],
            bold: colors.blue.dark[200],
            heavy: colors.blue.dark[100],
            ink: colors.blue.dark[50],
        },
        alt: {
            subtle: colors.pink.dark[950],
            faint: colors.pink.dark[900],
            soft: colors.pink.dark[800],
            muted: colors.pink.dark[700],
            gentle: colors.pink.dark[600],
            default: colors.pink.dark[500],
            vivid: colors.pink.dark[400],
            strong: colors.pink.dark[300],
            bold: colors.pink.dark[200],
            heavy: colors.pink.dark[100],
            ink: colors.pink.dark[50],
        },
        accent: {
            subtle: colors.purple.dark[950],
            faint: colors.purple.dark[900],
            soft: colors.purple.dark[800],
            muted: colors.purple.dark[700],
            gentle: colors.purple.dark[600],
            default: colors.purple.dark[500],
            vivid: colors.purple.dark[400],
            strong: colors.purple.dark[300],
            bold: colors.purple.dark[200],
            heavy: colors.purple.dark[100],
            ink: colors.purple.dark[50],
        },
        success: {
            subtle: colors.green.dark[950],
            faint: colors.green.dark[900],
            soft: colors.green.dark[800],
            muted: colors.green.dark[700],
            gentle: colors.green.dark[600],
            default: colors.green.dark[500],
            vivid: colors.green.dark[400],
            strong: colors.green.dark[300],
            bold: colors.green.dark[200],
            heavy: colors.green.dark[100],
            ink: colors.green.dark[50],
        },
        warning: {
            subtle: colors.orange.dark[950],
            faint: colors.orange.dark[900],
            soft: colors.orange.dark[800],
            muted: colors.orange.dark[700],
            gentle: colors.orange.dark[600],
            default: colors.orange.dark[500],
            vivid: colors.orange.dark[400],
            strong: colors.orange.dark[300],
            bold: colors.orange.dark[200],
            heavy: colors.orange.dark[100],
            ink: colors.orange.dark[50],
        },
        error: {
            subtle: colors.red.dark[950],
            faint: colors.red.dark[900],
            soft: colors.red.dark[800],
            muted: colors.red.dark[700],
            gentle: colors.red.dark[600],
            default: colors.red.dark[500],
            vivid: colors.red.dark[400],
            strong: colors.red.dark[300],
            bold: colors.red.dark[200],
            heavy: colors.red.dark[100],
            ink: colors.red.dark[50],
        },
    },
} as const;

export { themes };